name = "nfl-pickem-app"
compatibility_date = "2024-09-04"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = ".vercel/output/static"

# Preview environment
[env.preview]
vars = { NODE_ENV = "preview" }

# Production environment
[env.production.vars]
NODE_ENV = "production"
NEXTAUTH_URL = "https://pickem.leefamilysso.com"
THE_ODDS_API_BASE_URL = "https://api.the-odds-api.com/v4"
CURRENT_NFL_SEASON = "2025"
CURRENT_NFL_WEEK = "1"

# D1 database binding for production
[[env.production.d1_databases]]
binding = "DB"
database_name = "nfl-pickem-db"
database_id = "b85129d8-b27c-4c73-bd34-5314a881394b"

# KV storage for caching (optional)
# [[env.production.kv_namespaces]]
# binding = "CACHE"
# id = ""

# Secrets to be set via wrangler secret put
# THE_ODDS_API_KEY
# NEXTAUTH_SECRET