name = "nfl-pickem-app"
compatibility_date = "2024-09-04"
compatibility_flags = ["nodejs_compat"]

# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "nfl-pickem-db"
database_id = "b85129d8-b27c-4c73-bd34-5314a881394b"

# Environment variables
[vars]
NODE_ENV = "development"

# Preview environment
[env.preview]
[env.preview.vars]
NODE_ENV = "preview"

# Production environment
[env.production]
[env.production.vars]
NODE_ENV = "production"
NEXTAUTH_URL = "https://nfl-pickem-app-production.cybermattlee-llc.workers.dev"
THE_ODDS_API_BASE_URL = "https://api.the-odds-api.com/v4"
CURRENT_NFL_SEASON = "2025"
CURRENT_NFL_WEEK = "1"

# D1 database binding for production
[[env.production.d1_databases]]
binding = "DB"
database_name = "nfl-pickem-db"
database_id = "b85129d8-b27c-4c73-bd34-5314a881394b"

# KV storage for caching (optional)
# [[env.production.kv_namespaces]]
# binding = "CACHE"
# id = ""

# Cron triggers for game state automation
# During NFL season (Sept-Feb): Smart scheduling based on game days
[triggers]
crons = [
  # High-frequency during game days (Thu-Mon): Every 15 minutes
  "*/15 * * * 4",    # Thursday: Every 15 minutes (TNF games)
  "*/15 * * * 5",    # Friday: Every 15 minutes (rare games)
  "*/15 * * * 6",    # Saturday: Every 15 minutes (late season)
  "*/15 * * * 0",    # Sunday: Every 15 minutes (main game day)
  "*/15 * * * 1",    # Monday: Every 15 minutes (MNF games)
  
  # Lower frequency during off-game days (Tue-Wed): Every 2 hours  
  "0 */2 * * 2",     # Tuesday: Every 2 hours (maintenance)
  "0 */2 * * 3",     # Wednesday: Every 2 hours (preparation)
  
  # Special schedules for critical times
  "0 9,12,15,18,21 * 9-12,1-2 *",  # During NFL season months: 4 times daily
  "0 */6 * 3-8 *"    # Off-season: Every 6 hours for maintenance
]

# Secrets to be set via wrangler secret put
# THE_ODDS_API_KEY
# NEXTAUTH_SECRET