/**
 * E2E Tests: Pre-Seed User Accounts (Feature 003)
 *
 * Test Suite: Seed Verification
 * Purpose: Validate all four family members can authenticate and access their data
 *
 * IMPORTANT: These tests should FAIL before seeding (users have NULL passwords)
 *            and PASS after seeding (users have bcrypt password hashes)
 *
 * User Stories Covered:
 * - US1 (P1): Family Member Login - Authentication testing
 * - US2 (P2): Historical Picks Preservation - Data visibility testing
 * - US3 (P3): Consistent User Identity - UI consistency testing
 */

import { test, expect } from '@playwright/test';

// ===================================
// Test Configuration
// ===================================

const BASE_URL = 'https://pickem.cyberlees.dev';
const API_URL = 'https://nfl-pickem-app-production.m-de6.workers.dev';

// NOTE: These credentials come from .env.seed file generated by seed script
// For test execution, these would need to be set as environment variables
// or read from a secure test configuration file

interface UserCredentials {
  name: string;
  email: string;
  password: string;
  userId: string;
  expectedInitial: string;
  expectedPickCount: number;
}

const FAMILY_USERS: UserCredentials[] = [
  {
    name: 'Dad',
    email: 'Dad@example.com',
    password: process.env.DAD_PASSWORD || 'REPLACE_WITH_ACTUAL_PASSWORD',
    userId: 'dad-user-id',
    expectedInitial: 'D',
    expectedPickCount: 5,
  },
  {
    name: 'Mom',
    email: 'Mom@example.com',
    password: process.env.MOM_PASSWORD || 'REPLACE_WITH_ACTUAL_PASSWORD',
    userId: 'mom-user-id',
    expectedInitial: 'M',
    expectedPickCount: 5,
  },
  {
    name: 'TwoBow',
    email: 'Nick@example.com', // Email remains Nick@example.com
    password: process.env.TWOBOW_PASSWORD || 'REPLACE_WITH_ACTUAL_PASSWORD',
    userId: 'nick-user-id',
    expectedInitial: 'T',
    expectedPickCount: 5,
  },
  {
    name: 'RockyDaRock',
    email: 'RockyDaRock@example.com',
    password: process.env.ROCKY_PASSWORD || 'REPLACE_WITH_ACTUAL_PASSWORD',
    userId: 'rocky-user-id',
    expectedInitial: 'R',
    expectedPickCount: 5,
  },
];

// ===================================
// User Story 1: Family Member Login (P1)
// ===================================

test.describe('User Story 1: Family Member Login', () => {
  // T025: Test Dad authentication
  test('Dad can log in with seeded credentials', async ({ page }) => {
    const user = FAMILY_USERS[0]; // Dad

    // Navigate to sign-in page
    await page.goto(`${BASE_URL}/signin`);

    // Fill in credentials
    await page.fill('input[type="email"]', user.email);
    await page.fill('input[type="password"]', user.password);

    // Click sign in button
    await page.click('button[type="submit"]');

    // Wait for navigation to complete
    await page.waitForURL(`${BASE_URL}/games`, { timeout: 5000 });

    // Verify redirect to games page
    expect(page.url()).toContain('/games');

    // Verify user is authenticated (check for sign out button or user menu)
    const signOutButton = page.locator('text="Sign Out"').or(page.locator('button:has-text("Sign")'));
    await expect(signOutButton).toBeVisible({ timeout: 3000 });
  });

  // T026: Test Mom authentication
  test('Mom can log in with seeded credentials', async ({ page }) => {
    const user = FAMILY_USERS[1]; // Mom

    await page.goto(`${BASE_URL}/signin`);
    await page.fill('input[type="email"]', user.email);
    await page.fill('input[type="password"]', user.password);
    await page.click('button[type="submit"]');

    await page.waitForURL(`${BASE_URL}/games`, { timeout: 5000 });
    expect(page.url()).toContain('/games');

    const signOutButton = page.locator('text="Sign Out"').or(page.locator('button:has-text("Sign")'));
    await expect(signOutButton).toBeVisible({ timeout: 3000 });
  });

  // T027: Test TwoBow authentication
  test('TwoBow can log in with seeded credentials', async ({ page }) => {
    const user = FAMILY_USERS[2]; // TwoBow

    await page.goto(`${BASE_URL}/signin`);
    await page.fill('input[type="email"]', user.email);
    await page.fill('input[type="password"]', user.password);
    await page.click('button[type="submit"]');

    await page.waitForURL(`${BASE_URL}/games`, { timeout: 5000 });
    expect(page.url()).toContain('/games');

    const signOutButton = page.locator('text="Sign Out"').or(page.locator('button:has-text("Sign")'));
    await expect(signOutButton).toBeVisible({ timeout: 3000 });
  });

  // T028: Test RockyDaRock authentication
  test('RockyDaRock can log in with seeded credentials', async ({ page }) => {
    const user = FAMILY_USERS[3]; // RockyDaRock

    await page.goto(`${BASE_URL}/signin`);
    await page.fill('input[type="email"]', user.email);
    await page.fill('input[type="password"]', user.password);
    await page.click('button[type="submit"]');

    await page.waitForURL(`${BASE_URL}/games`, { timeout: 5000 });
    expect(page.url()).toContain('/games');

    const signOutButton = page.locator('text="Sign Out"').or(page.locator('button:has-text("Sign")'));
    await expect(signOutButton).toBeVisible({ timeout: 3000 });
  });

  // T029: Test login redirects to games page
  test('Login redirects to games page after authentication', async ({ page }) => {
    const user = FAMILY_USERS[0]; // Use Dad for this test

    await page.goto(`${BASE_URL}/signin`);
    await page.fill('input[type="email"]', user.email);
    await page.fill('input[type="password"]', user.password);

    // Click submit and wait for redirect
    await Promise.all([
      page.waitForURL(`${BASE_URL}/games`, { timeout: 5000 }),
      page.click('button[type="submit"]'),
    ]);

    // Verify final URL is games page
    expect(page.url()).toBe(`${BASE_URL}/games`);

    // Verify games page content is visible
    const gamesPageHeader = page.locator('h1, h2').filter({ hasText: /Games|Week|Picks/i }).first();
    await expect(gamesPageHeader).toBeVisible({ timeout: 3000 });
  });
});

// ===================================
// User Story 2: Historical Picks Preservation (P2)
// ===================================

test.describe('User Story 2: Historical Picks Preservation', () => {
  // T033: Test Dad sees historical picks
  test('Dad sees 5 historical picks after seeding', async ({ page }) => {
    const user = FAMILY_USERS[0]; // Dad

    // Login first
    await page.goto(`${BASE_URL}/signin`);
    await page.fill('input[type="email"]', user.email);
    await page.fill('input[type="password"]', user.password);
    await page.click('button[type="submit"]');
    await page.waitForURL(`${BASE_URL}/games`, { timeout: 5000 });

    // Navigate to games page (should already be there)
    await page.goto(`${BASE_URL}/games`);

    // Wait for games to load
    await page.waitForSelector('[data-testid="game-card"], .game-card, [class*="game"]', { timeout: 10000 });

    // Count visible picks made by user (look for picked team indicators)
    const picks = page.locator('[data-testid="user-pick"], [class*="pick-indicator"], [class*="selected-team"]');
    const pickCount = await picks.count();

    // Verify at least 5 picks are visible (historical data)
    expect(pickCount).toBeGreaterThanOrEqual(user.expectedPickCount);
  });

  // T034: Test Mom sees historical picks
  test('Mom sees 5 historical picks after seeding', async ({ page }) => {
    const user = FAMILY_USERS[1]; // Mom

    await page.goto(`${BASE_URL}/signin`);
    await page.fill('input[type="email"]', user.email);
    await page.fill('input[type="password"]', user.password);
    await page.click('button[type="submit"]');
    await page.waitForURL(`${BASE_URL}/games`, { timeout: 5000 });

    await page.goto(`${BASE_URL}/games`);
    await page.waitForSelector('[data-testid="game-card"], .game-card, [class*="game"]', { timeout: 10000 });

    const picks = page.locator('[data-testid="user-pick"], [class*="pick-indicator"], [class*="selected-team"]');
    const pickCount = await picks.count();

    expect(pickCount).toBeGreaterThanOrEqual(user.expectedPickCount);
  });

  // T035: Test TwoBow sees historical picks
  test('TwoBow sees 5 historical picks after seeding', async ({ page }) => {
    const user = FAMILY_USERS[2]; // TwoBow

    await page.goto(`${BASE_URL}/signin`);
    await page.fill('input[type="email"]', user.email);
    await page.fill('input[type="password"]', user.password);
    await page.click('button[type="submit"]');
    await page.waitForURL(`${BASE_URL}/games`, { timeout: 5000 });

    await page.goto(`${BASE_URL}/games`);
    await page.waitForSelector('[data-testid="game-card"], .game-card, [class*="game"]', { timeout: 10000 });

    const picks = page.locator('[data-testid="user-pick"], [class*="pick-indicator"], [class*="selected-team"]');
    const pickCount = await picks.count();

    expect(pickCount).toBeGreaterThanOrEqual(user.expectedPickCount);
  });

  // T036: Test RockyDaRock sees historical picks
  test('RockyDaRock sees 5 historical picks after seeding', async ({ page }) => {
    const user = FAMILY_USERS[3]; // RockyDaRock

    await page.goto(`${BASE_URL}/signin`);
    await page.fill('input[type="email"]', user.email);
    await page.fill('input[type="password"]', user.password);
    await page.click('button[type="submit"]');
    await page.waitForURL(`${BASE_URL}/games`, { timeout: 5000 });

    await page.goto(`${BASE_URL}/games`);
    await page.waitForSelector('[data-testid="game-card"], .game-card, [class*="game"]', { timeout: 10000 });

    const picks = page.locator('[data-testid="user-pick"], [class*="pick-indicator"], [class*="selected-team"]');
    const pickCount = await picks.count();

    expect(pickCount).toBeGreaterThanOrEqual(user.expectedPickCount);
  });

  // T037: Test leaderboard points unchanged
  test('Leaderboard points unchanged after seeding', async ({ page }) => {
    // Can use any user to view leaderboard
    const user = FAMILY_USERS[0];

    await page.goto(`${BASE_URL}/signin`);
    await page.fill('input[type="email"]', user.email);
    await page.fill('input[type="password"]', user.password);
    await page.click('button[type="submit"]');
    await page.waitForURL(`${BASE_URL}/games`, { timeout: 5000 });

    // Navigate to leaderboard
    await page.goto(`${BASE_URL}/leaderboard`);

    // Wait for leaderboard to load
    await page.waitForSelector('[data-testid="leaderboard"], .leaderboard, table', { timeout: 5000 });

    // Verify all 4 family members are visible on leaderboard
    for (const familyUser of FAMILY_USERS) {
      const userRow = page.locator(`text="${familyUser.name}"`);
      await expect(userRow).toBeVisible({ timeout: 3000 });
    }

    // Verify points/standings are visible (non-zero)
    const pointsElements = page.locator('[data-testid="points"], [class*="points"], td:has-text("pts"), td:has-text("points")');
    const pointsCount = await pointsElements.count();
    expect(pointsCount).toBeGreaterThan(0);
  });

  // T038: Test historical pick correctness indicators
  test('Historical pick correctness indicators preserved', async ({ page }) => {
    const user = FAMILY_USERS[0];

    await page.goto(`${BASE_URL}/signin`);
    await page.fill('input[type="email"]', user.email);
    await page.fill('input[type="password"]', user.password);
    await page.click('button[type="submit"]');
    await page.waitForURL(`${BASE_URL}/games`, { timeout: 5000 });

    await page.goto(`${BASE_URL}/games`);
    await page.waitForSelector('[data-testid="game-card"], .game-card, [class*="game"]', { timeout: 10000 });

    // Look for correct/incorrect indicators (checkmarks, X marks, green/red colors)
    const correctIndicators = page.locator('[data-testid="pick-correct"], [class*="correct"], [class*="win"], .text-green');
    const incorrectIndicators = page.locator('[data-testid="pick-incorrect"], [class*="incorrect"], [class*="loss"], .text-red');

    const correctCount = await correctIndicators.count();
    const incorrectCount = await incorrectIndicators.count();

    // Verify that some picks have correctness indicators (historical data exists)
    const totalIndicators = correctCount + incorrectCount;
    expect(totalIndicators).toBeGreaterThan(0);
  });
});

// ===================================
// User Story 3: Consistent User Identity (P3)
// ===================================

test.describe('User Story 3: Consistent User Identity', () => {
  // T041: Test family pick initials display
  test('Family pick initials display correctly on game cards', async ({ page }) => {
    const user = FAMILY_USERS[0]; // Login as Dad to view game cards

    await page.goto(`${BASE_URL}/signin`);
    await page.fill('input[type="email"]', user.email);
    await page.fill('input[type="password"]', user.password);
    await page.click('button[type="submit"]');
    await page.waitForURL(`${BASE_URL}/games`, { timeout: 5000 });

    await page.goto(`${BASE_URL}/games`);
    await page.waitForSelector('[data-testid="game-card"], .game-card, [class*="game"]', { timeout: 10000 });

    // Look for family pick indicators with initials
    // These are typically colored circles with letters: D, M, T, R
    const familyPickIndicators = page.locator('[data-testid="family-picks"], [class*="family-pick"], [class*="pick-initial"]');

    // Verify at least some family pick indicators are visible
    const indicatorCount = await familyPickIndicators.count();
    expect(indicatorCount).toBeGreaterThan(0);

    // Check for specific initials (D, M, T, R) in the family pick section
    for (const familyUser of FAMILY_USERS) {
      const initialIndicator = page.locator(`text="${familyUser.expectedInitial}"`).first();
      // Note: May not be visible if that user hasn't made picks for visible games
      // So we just check if it exists in the DOM
      const exists = (await initialIndicator.count()) > 0;
      console.log(`${familyUser.name} initial "${familyUser.expectedInitial}" exists: ${exists}`);
    }
  });

  // T042: Test user initials match display names
  test('User initials match display names (D, M, T, R)', async ({ page }) => {
    const user = FAMILY_USERS[0];

    await page.goto(`${BASE_URL}/signin`);
    await page.fill('input[type="email"]', user.email);
    await page.fill('input[type="password"]', user.password);
    await page.click('button[type="submit"]');
    await page.waitForURL(`${BASE_URL}/games`, { timeout: 5000 });

    // Navigate to leaderboard to see all user display names
    await page.goto(`${BASE_URL}/leaderboard`);
    await page.waitForSelector('[data-testid="leaderboard"], .leaderboard, table', { timeout: 5000 });

    // Verify each user's display name matches expected
    for (const familyUser of FAMILY_USERS) {
      const userNameElement = page.locator(`text="${familyUser.name}"`);
      await expect(userNameElement).toBeVisible({ timeout: 3000 });

      // Verify first character of name matches expected initial
      const displayedName = await userNameElement.textContent();
      expect(displayedName?.charAt(0).toUpperCase()).toBe(familyUser.expectedInitial);
    }
  });

  // T043: Test user colors match frontend mapping
  test('User colors match hardcoded frontend mapping', async ({ page }) => {
    const user = FAMILY_USERS[0];

    await page.goto(`${BASE_URL}/signin`);
    await page.fill('input[type="email"]', user.email);
    await page.fill('input[type="password"]', user.password);
    await page.click('button[type="submit"]');
    await page.waitForURL(`${BASE_URL}/games`, { timeout: 5000 });

    await page.goto(`${BASE_URL}/games`);
    await page.waitForSelector('[data-testid="game-card"], .game-card, [class*="game"]', { timeout: 10000 });

    // Expected colors from data-model.md:
    // Dad: Blue (#3B82F6)
    // Mom: Pink (#EC4899)
    // TwoBow: Green (#10B981)
    // RockyDaRock: Orange (#F97316)

    const expectedColors: Record<string, string> = {
      Dad: '#3B82F6',
      Mom: '#EC4899',
      TwoBow: '#10B981',
      RockyDaRock: '#F97316',
    };

    // Look for family pick initial elements and verify their colors
    const familyPickElements = page.locator('[data-testid="family-pick-initial"], [class*="family-pick-initial"], [class*="pick-circle"]');

    // Note: Exact color matching requires inspecting computed styles
    // This is a basic check that colored elements exist
    const elementCount = await familyPickElements.count();
    expect(elementCount).toBeGreaterThan(0);

    console.log(`Found ${elementCount} family pick initial elements with colors`);
  });
});

// ===================================
// Utility Test: API Authentication
// ===================================

test.describe('API Authentication Tests', () => {
  test('All users can authenticate via API', async ({ request }) => {
    for (const user of FAMILY_USERS) {
      const response = await request.post(`${API_URL}/api/auth/signin`, {
        data: {
          email: user.email,
          password: user.password,
        },
      });

      // Verify successful authentication
      expect(response.status()).toBe(200);

      // Verify JWT token is returned
      const responseBody = await response.json();
      expect(responseBody).toHaveProperty('token');
      expect(responseBody).toHaveProperty('user');
      expect(responseBody.user.id).toBe(user.userId);

      console.log(`✓ ${user.name} authenticated successfully via API`);
    }
  });
});
