/**
 * Component Showcase - Visual Test Page
 *
 * This file demonstrates all states of PickSelector and GameResult components.
 * NOT for production - use for development/testing only.
 *
 * To use: Import this component in a test route or development page.
 */

import React, { useState } from 'react';
import PickSelector from '../PickSelector';
import GameResult from '../GameResult';

const mockTeams = {
  chiefs: {
    id: 'kc-chiefs-001',
    name: 'Kansas City Chiefs',
    abbreviation: 'KC',
    logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/kc.png',
  },
  eagles: {
    id: 'phi-eagles-001',
    name: 'Philadelphia Eagles',
    abbreviation: 'PHI',
    logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/phi.png',
  },
  ravens: {
    id: 'bal-ravens-001',
    name: 'Baltimore Ravens',
    abbreviation: 'BAL',
    logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/bal.png',
  },
  cowboys: {
    id: 'dal-cowboys-001',
    name: 'Dallas Cowboys',
    abbreviation: 'DAL',
    logoUrl: 'https://a.espncdn.com/i/teamlogos/nfl/500/dal.png',
  },
};

export default function ComponentShowcase() {
  const [pick1, setPick1] = useState<string | undefined>(undefined);
  const [pick2, setPick2] = useState<string | undefined>(mockTeams.chiefs.id);
  const [pick3, setPick3] = useState<string | undefined>(mockTeams.eagles.id);

  const mockPickSubmit = async (teamId: string) => {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1000));

    // Simulate random error (10% chance)
    if (Math.random() < 0.1) {
      throw new Error('Network error: Could not save pick');
    }

    console.log('Pick submitted:', teamId);
  };

  return (
    <div className="min-h-screen bg-gray-50 p-4">
      <div className="mx-auto max-w-4xl space-y-8">
        {/* Header */}
        <div className="rounded-lg bg-white p-6 shadow">
          <h1 className="text-3xl font-bold text-gray-900">Component Showcase</h1>
          <p className="mt-2 text-gray-600">
            Visual testing for PickSelector and GameResult components
          </p>
        </div>

        {/* PickSelector Examples */}
        <section className="space-y-6">
          <h2 className="text-2xl font-bold text-gray-900">PickSelector Component</h2>

          {/* Default State */}
          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="mb-4 text-lg font-semibold text-gray-900">
              1. Default State (No Pick)
            </h3>
            <PickSelector
              game={{
                id: 'game-001',
                homeTeam: mockTeams.chiefs,
                awayTeam: mockTeams.eagles,
                isLocked: false,
              }}
              currentPick={pick1 ? { teamId: pick1 } : undefined}
              onPickSubmit={async (teamId) => {
                await mockPickSubmit(teamId);
                setPick1(teamId);
              }}
            />
          </div>

          {/* With Existing Pick */}
          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="mb-4 text-lg font-semibold text-gray-900">
              2. With Existing Pick (Chiefs Selected)
            </h3>
            <PickSelector
              game={{
                id: 'game-002',
                homeTeam: mockTeams.chiefs,
                awayTeam: mockTeams.eagles,
                isLocked: false,
              }}
              currentPick={{ teamId: pick2 }}
              onPickSubmit={async (teamId) => {
                await mockPickSubmit(teamId);
                setPick2(teamId);
              }}
            />
          </div>

          {/* Locked Game */}
          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="mb-4 text-lg font-semibold text-gray-900">
              3. Locked Game (Cannot Change Pick)
            </h3>
            <PickSelector
              game={{
                id: 'game-003',
                homeTeam: mockTeams.ravens,
                awayTeam: mockTeams.cowboys,
                isLocked: true,
              }}
              currentPick={{ teamId: mockTeams.ravens.id }}
              onPickSubmit={mockPickSubmit}
            />
          </div>

          {/* Auto-Generated Pick */}
          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="mb-4 text-lg font-semibold text-gray-900">
              4. Auto-Generated Pick (AUTO Badge)
            </h3>
            <PickSelector
              game={{
                id: 'game-004',
                homeTeam: mockTeams.chiefs,
                awayTeam: mockTeams.eagles,
                isLocked: true,
              }}
              currentPick={{ teamId: pick3, autoGenerated: true }}
              onPickSubmit={mockPickSubmit}
            />
          </div>

          {/* Disabled State */}
          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="mb-4 text-lg font-semibold text-gray-900">
              5. Disabled State (External)
            </h3>
            <PickSelector
              game={{
                id: 'game-005',
                homeTeam: mockTeams.ravens,
                awayTeam: mockTeams.cowboys,
                isLocked: false,
              }}
              disabled={true}
              onPickSubmit={mockPickSubmit}
            />
          </div>
        </section>

        {/* GameResult Examples */}
        <section className="space-y-6">
          <h2 className="text-2xl font-bold text-gray-900">GameResult Component</h2>

          {/* Correct Pick */}
          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="mb-4 text-lg font-semibold text-gray-900">
              1. Correct Pick (Green Border + Checkmark)
            </h3>
            <GameResult
              game={{
                id: 'game-101',
                homeTeam: mockTeams.chiefs,
                awayTeam: mockTeams.eagles,
                homeScore: 38,
                awayScore: 35,
                homeSpread: -3.5,
                overUnder: 51.5,
                status: 'final',
                winnerTeamId: mockTeams.chiefs.id,
              }}
              userPick={{
                teamId: mockTeams.chiefs.id,
                isCorrect: true,
              }}
            />
          </div>

          {/* Incorrect Pick */}
          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="mb-4 text-lg font-semibold text-gray-900">
              2. Incorrect Pick (Red Border + X)
            </h3>
            <GameResult
              game={{
                id: 'game-102',
                homeTeam: mockTeams.ravens,
                awayTeam: mockTeams.cowboys,
                homeScore: 24,
                awayScore: 27,
                homeSpread: 2.5,
                overUnder: 47.5,
                status: 'final',
                winnerTeamId: mockTeams.cowboys.id,
              }}
              userPick={{
                teamId: mockTeams.ravens.id,
                isCorrect: false,
              }}
            />
          </div>

          {/* No Pick */}
          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="mb-4 text-lg font-semibold text-gray-900">
              3. No Pick Made (Gray Border)
            </h3>
            <GameResult
              game={{
                id: 'game-103',
                homeTeam: mockTeams.chiefs,
                awayTeam: mockTeams.eagles,
                homeScore: 31,
                awayScore: 17,
                homeSpread: -5.5,
                overUnder: 48.5,
                status: 'final',
                winnerTeamId: mockTeams.chiefs.id,
              }}
            />
          </div>

          {/* In Progress */}
          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="mb-4 text-lg font-semibold text-gray-900">
              4. In Progress (Live Game)
            </h3>
            <GameResult
              game={{
                id: 'game-104',
                homeTeam: mockTeams.ravens,
                awayTeam: mockTeams.cowboys,
                homeScore: 14,
                awayScore: 10,
                homeSpread: 3.5,
                overUnder: 45.5,
                status: 'in_progress',
              }}
              userPick={{
                teamId: mockTeams.ravens.id,
              }}
            />
          </div>

          {/* High Scoring Game */}
          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="mb-4 text-lg font-semibold text-gray-900">
              5. High Scoring Game (No Spread/O/U)
            </h3>
            <GameResult
              game={{
                id: 'game-105',
                homeTeam: mockTeams.chiefs,
                awayTeam: mockTeams.ravens,
                homeScore: 52,
                awayScore: 49,
                status: 'final',
                winnerTeamId: mockTeams.chiefs.id,
              }}
              userPick={{
                teamId: mockTeams.chiefs.id,
                isCorrect: true,
              }}
            />
          </div>

          {/* Tie Game */}
          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="mb-4 text-lg font-semibold text-gray-900">
              6. Tie Game (No Winner)
            </h3>
            <GameResult
              game={{
                id: 'game-106',
                homeTeam: mockTeams.eagles,
                awayTeam: mockTeams.cowboys,
                homeScore: 20,
                awayScore: 20,
                homeSpread: -1.5,
                overUnder: 42.5,
                status: 'final',
              }}
              userPick={{
                teamId: mockTeams.eagles.id,
              }}
            />
          </div>
        </section>

        {/* Integration Example */}
        <section className="space-y-6">
          <h2 className="text-2xl font-bold text-gray-900">Integration Example</h2>

          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="mb-4 text-lg font-semibold text-gray-900">
              Complete Game Card Flow
            </h3>
            <p className="mb-4 text-sm text-gray-600">
              This demonstrates how PickSelector and GameResult would be used together in a
              real GameCard component.
            </p>

            {/* Scheduled Game */}
            <div className="mb-6">
              <div className="mb-2 text-xs font-medium uppercase text-gray-500">
                Scheduled Game (Pick Selection)
              </div>
              <PickSelector
                game={{
                  id: 'game-201',
                  homeTeam: mockTeams.chiefs,
                  awayTeam: mockTeams.eagles,
                  isLocked: false,
                }}
                currentPick={pick1 ? { teamId: pick1 } : undefined}
                onPickSubmit={async (teamId) => {
                  await mockPickSubmit(teamId);
                  setPick1(teamId);
                }}
              />
            </div>

            {/* Completed Game */}
            <div>
              <div className="mb-2 text-xs font-medium uppercase text-gray-500">
                Completed Game (Result Display)
              </div>
              <GameResult
                game={{
                  id: 'game-202',
                  homeTeam: mockTeams.ravens,
                  awayTeam: mockTeams.cowboys,
                  homeScore: 31,
                  awayScore: 24,
                  homeSpread: 2.5,
                  overUnder: 48.5,
                  status: 'final',
                  winnerTeamId: mockTeams.ravens.id,
                }}
                userPick={{
                  teamId: mockTeams.ravens.id,
                  isCorrect: true,
                }}
              />
            </div>
          </div>
        </section>

        {/* Accessibility Testing */}
        <section className="space-y-6">
          <h2 className="text-2xl font-bold text-gray-900">Accessibility Features</h2>

          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="mb-4 text-lg font-semibold text-gray-900">
              Testing Instructions
            </h3>
            <ul className="space-y-2 text-sm text-gray-700">
              <li className="flex items-start gap-2">
                <span className="font-medium">⌨️ Keyboard:</span>
                <span>Use Arrow keys, Enter, and Space to navigate PickSelector</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="font-medium">🔍 Screen Reader:</span>
                <span>All components have proper ARIA labels and roles</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="font-medium">👆 Touch:</span>
                <span>All buttons have 44x44px minimum touch targets</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="font-medium">🎨 Color:</span>
                <span>Icons + text used (not color alone) for status indicators</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="font-medium">📱 Mobile:</span>
                <span>Resize to 375px width to test mobile layouts</span>
              </li>
            </ul>
          </div>
        </section>

        {/* Footer */}
        <div className="rounded-lg bg-gray-800 p-6 text-white shadow">
          <h3 className="mb-2 text-lg font-semibold">Development Notes</h3>
          <ul className="space-y-1 text-sm text-gray-300">
            <li>• PickSelector uses optimistic updates (instant UI feedback)</li>
            <li>• GameResult automatically computes winner if not provided</li>
            <li>• Both components are wrapped in error boundaries</li>
            <li>• All components are memoized for performance</li>
            <li>• Open browser console to see pick submission logs</li>
            <li>• 10% chance of simulated API error for error state testing</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
