import React, { useEffect, useMemo, useState } from 'react';
import { ApiClient } from '../utils/api';
import {
  CheckCircleIcon,
  XCircleIcon,
  ClockIcon as ClockIconSolid,
  SparklesIcon,
  ExclamationTriangleIcon
} from '@heroicons/react/24/solid';

type Team = {
  id: string;
  name: string;
  abbreviation: string;
  logoUrl: string;
};

type Game = {
  id: string;
  homeTeamId: string;
  awayTeamId: string;
  homeTeam: Team;
  awayTeam: Team;
  startTime: string;
  week: number;
  season: number;
  status: string;
  homeScore: number | null;
  awayScore: number | null;
  homeSpread: number | null;
  overUnder: number | null;
};

type PickHistoryItem = {
  id: string;
  gameId: string;
  userId: string;
  selectedTeamId: string;
  isAutoGenerated: boolean;
  createdAt: string;
  game: Game;
  isCorrect: boolean | null;
};

type FilterMode = 'all' | 'correct' | 'incorrect' | 'auto';

const DEFAULT_SEASON = 2025;

export function PickHistoryPage() {
  const [season, setSeason] = useState<number>(DEFAULT_SEASON);
  const [week, setWeek] = useState<number>(1);
  const [filterMode, setFilterMode] = useState<FilterMode>('all');
  const [data, setData] = useState<PickHistoryItem[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  // Load all picks for the season and apply week/filter client-side (per T061)
  useEffect(() => {
    let isCancelled = false;
    const load = async () => {
      setLoading(true);
      setError(null);
      try {
        // Fetch all picks for the selected season (no week param)
        const response = await ApiClient.get(`/api/picks/history?season=${season}`);
        if (!response || !response.success) {
          throw new Error(response?.error || 'Failed to load pick history');
        }
        const items: PickHistoryItem[] = response.data || [];
        if (!isCancelled) {
          // Sort descending by week, then by game start time
          const sorted = [...items].sort((a, b) => {
            if (a.game.week !== b.game.week) return b.game.week - a.game.week;
            return new Date(b.game.startTime).getTime() - new Date(a.game.startTime).getTime();
          });
          setData(sorted);
        }
      } catch (e: any) {
        if (!isCancelled) {
          setError(e?.message || 'Failed to load pick history');
        }
      } finally {
        if (!isCancelled) setLoading(false);
      }
    };
    load();
    return () => {
      isCancelled = true;
    };
  }, [season]);

  // Client-side filter by week + filter mode
  const filtered = useMemo(() => {
    const byWeek = data.filter(item => item.game.week === week);
    switch (filterMode) {
      case 'correct':
        return byWeek.filter(item => item.isCorrect === true);
      case 'incorrect':
        return byWeek.filter(item => item.isCorrect === false);
      case 'auto':
        return byWeek.filter(item => item.isAutoGenerated);
      default:
        return byWeek;
    }
  }, [data, week, filterMode]);

  // Group filtered picks by week (will typically be one group due to selected week)
  const groupedByWeek = useMemo(() => {
    const map = new Map<number, PickHistoryItem[]>();
    for (const item of filtered) {
      const arr = map.get(item.game.week) || [];
      arr.push(item);
      map.set(item.game.week, arr);
    }
    // Sort games in each week by start time ascending
    for (const [w, arr] of map.entries()) {
      arr.sort((a, b) => new Date(a.game.startTime).getTime() - new Date(b.game.startTime).getTime());
      map.set(w, arr);
    }
    // Sort weeks descending to keep consistent with historical view
    return Array.from(map.entries()).sort((a, b) => b[0] - a[0]);
  }, [filtered]);

  // Stats for selected week (filtered set)
  const statsForWeek = useMemo(() => {
    const total = filtered.length;
    const correct = filtered.filter(i => i.isCorrect === true).length;
    const pct = total > 0 ? Math.round((correct / total) * 100) : 0;
    return { total, correct, pct };
  }, [filtered]);

  // Best week across the season (based on correct picks)
  const bestWeekAcrossSeason = useMemo(() => {
    // Compute using all season data (ignoring filterMode / selected week)
    const byWeek = new Map<number, { total: number; correct: number }>();
    for (const item of data) {
      const wk = item.game.week;
      const entry = byWeek.get(wk) || { total: 0, correct: 0 };
      entry.total += 1;
      if (item.isCorrect === true) entry.correct += 1;
      byWeek.set(wk, entry);
    }
    let bestWeek: number | null = null;
    let bestCorrect = -1;
    for (const [wk, { correct }] of byWeek.entries()) {
      if (correct > bestCorrect || (correct === bestCorrect && bestWeek !== null && wk < bestWeek)) {
        bestCorrect = correct;
        bestWeek = wk;
      }
    }
    return bestWeek !== null ? { week: bestWeek, correct: bestCorrect } : null;
  }, [data]);

  const renderPickCard = (pick: PickHistoryItem) => {
    const { game } = pick;
    const isFinal = game.status?.toLowerCase() === 'final' || (game.homeScore !== null && game.awayScore !== null);
    const selectedIsHome = pick.selectedTeamId === game.homeTeamId;
    const selectedTeam = selectedIsHome ? game.homeTeam : game.awayTeam;

    const resultIcon =
      pick.isCorrect === true ? (
        <CheckCircleIcon className="w-5 h-5 text-green-600" />
      ) : pick.isCorrect === false ? (
        <XCircleIcon className="w-5 h-5 text-red-600" />
      ) : (
        <ClockIconSolid className="w-5 h-5 text-amber-500" />
      );

    const scoreText =
      game.homeScore !== null && game.awayScore !== null
        ? `${game.awayTeam.abbreviation} ${game.awayScore} @ ${game.homeTeam.abbreviation} ${game.homeScore}`
        : `${game.awayTeam.abbreviation} @ ${game.homeTeam.abbreviation}`;

    const statusText = isFinal ? 'Final' : (game.status || 'Scheduled');

    const pickBadge = pick.isAutoGenerated ? (
      <span className="ml-2 inline-flex items-center text-[10px] px-2 py-0.5 rounded-full bg-purple-100 text-purple-700 border border-purple-200">
        <SparklesIcon className="w-3 h-3 mr-1" />
        AUTO
      </span>
    ) : null;

    const correctnessBg =
      pick.isCorrect === true
        ? 'border-green-200 bg-green-50'
        : pick.isCorrect === false
          ? 'border-red-200 bg-red-50'
          : 'border-slate-200 bg-white';

    return (
      <div
        key={pick.id}
        className={`flex flex-col sm:flex-row items-start sm:items-center justify-between p-4 rounded-lg border ${correctnessBg} shadow-sm`}
      >
        {/* Left side: teams and scores */}
        <div className="flex items-start sm:items-center gap-4 w-full">
          <div className="flex items-center gap-3">
            <img src={game.awayTeam.logoUrl} alt={game.awayTeam.abbreviation} loading="lazy" decoding="async" className="w-8 h-8 rounded-full bg-white border" />
            <span className="text-sm font-medium">{game.awayTeam.abbreviation}</span>
          </div>
          <div className="text-xs text-slate-500">at</div>
          <div className="flex items-center gap-3">
            <img src={game.homeTeam.logoUrl} alt={game.homeTeam.abbreviation} loading="lazy" decoding="async" className="w-8 h-8 rounded-full bg-white border" />
            <span className="text-sm font-medium">{game.homeTeam.abbreviation}</span>
          </div>
        </div>

        {/* Right side: pick/result */}
        <div className="mt-3 sm:mt-0 flex flex-col sm:flex-row sm:items-center gap-2 w-full sm:w-auto">
          <div className="text-xs text-slate-500">{new Date(game.startTime).toLocaleString()}</div>
          <div className="text-xs text-slate-500 sm:text-right">{scoreText} • {statusText}</div>

          <div className="flex items-center gap-2 sm:ml-4">
            {resultIcon}
            <span className="text-sm font-medium">
              Pick: {selectedTeam.abbreviation}
            </span>
            {pickBadge}
          </div>
        </div>
      </div>
    );
  };

  // Loading state
  if (loading) {
    return (
      <div className="space-y-4">
        <div className="flex justify-between items-center mb-4">
          <div className="h-8 w-36 bg-slate-200 rounded animate-pulse" />
          <div className="h-8 w-48 bg-slate-200 rounded animate-pulse" />
        </div>
        {[...Array(3)].map((_, i) => (
          <div key={i} className="bg-white rounded-lg border p-6 animate-pulse">
            <div className="h-4 w-40 bg-slate-200 rounded mb-4" />
            <div className="h-20 w-full bg-slate-100 rounded" />
          </div>
        ))}
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 text-red-700 rounded-lg p-4">
        <div className="flex items-start">
          <ExclamationTriangleIcon className="w-5 h-5 mt-0.5 mr-2" />
          <div className="flex-1">
            <div className="font-semibold">Failed to load Pick History</div>
            <div className="text-sm mt-1">{error}</div>
            <button
              onClick={() => {
                // Trigger re-fetch by toggling season temporarily
                setSeason(s => (s === DEFAULT_SEASON ? DEFAULT_SEASON : DEFAULT_SEASON));
              }}
              className="mt-3 px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm"
            >
              Retry
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header / Controls */}
      <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-4">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold">Pick History</h1>
          <div className="text-slate-500 text-sm mt-1">Review your picks, outcomes, and auto-generated selections</div>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          {/* Season selector */}
          <div className="flex items-center gap-2">
            <label className="text-sm font-medium">Season:</label>
            <select
              value={season}
              onChange={(e) => setSeason(parseInt(e.target.value))}
              className="px-3 py-2 border rounded-lg bg-white text-sm"
            >
              <option value={2025}>2025</option>
              <option value={2024}>2024</option>
            </select>
          </div>

          {/* Week selector */}
          <div className="flex items-center gap-2">
            <label className="text-sm font-medium">Week:</label>
            <select
              value={week}
              onChange={(e) => setWeek(parseInt(e.target.value))}
              className="px-3 py-2 border rounded-lg bg-white text-sm"
            >
              {Array.from({ length: 18 }, (_, i) => i + 1).map(w => (
                <option key={w} value={w}>Week {w}</option>
              ))}
            </select>
          </div>

          {/* Filter toggle */}
          <div className="flex bg-slate-100 rounded-lg p-1">
            {(['all', 'correct', 'incorrect', 'auto'] as FilterMode[]).map(mode => (
              <button
                key={mode}
                onClick={() => setFilterMode(mode)}
                className={`px-3 py-1.5 text-xs font-medium rounded-md transition-colors ${
                  filterMode === mode
                    ? 'bg-white text-slate-900 shadow-sm'
                    : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                {mode === 'all' ? 'All' :
                 mode === 'correct' ? 'Correct' :
                 mode === 'incorrect' ? 'Incorrect' : 'Auto'}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Stats Summary (T062) */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white rounded-xl border border-slate-200 p-5 text-center shadow-sm">
          <div className="text-3xl font-bold text-slate-900">{statsForWeek.total}</div>
          <div className="text-sm text-slate-500 mt-1">Total Picks (Week {week})</div>
        </div>
        <div className="bg-white rounded-xl border border-slate-200 p-5 text-center shadow-sm">
          <div className="text-3xl font-bold text-green-600">{statsForWeek.correct}</div>
          <div className="text-sm text-slate-500 mt-1">Correct Picks (Week {week})</div>
        </div>
        <div className="bg-white rounded-xl border border-slate-200 p-5 text-center shadow-sm">
          <div className="text-3xl font-bold text-blue-600">{statsForWeek.pct}%</div>
          <div className="text-sm text-slate-500 mt-1">Win Percentage (Week {week})</div>
        </div>
        <div className="bg-white rounded-xl border border-slate-200 p-5 text-center shadow-sm">
          <div className="text-3xl font-bold text-amber-600">
            {bestWeekAcrossSeason ? `W${bestWeekAcrossSeason.week}` : '—'}
          </div>
          <div className="text-sm text-slate-500 mt-1">
            Best Week (Season) {bestWeekAcrossSeason ? `• ${bestWeekAcrossSeason.correct} correct` : ''}
          </div>
        </div>
      </div>

      {/* Picks grouped by week (T059) */}
      {groupedByWeek.length === 0 ? (
        <div className="text-center py-12 bg-white rounded-lg border">
          <svg className="w-16 h-16 text-slate-300 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3M5 11h14M5 19h14M7 11v8m10-8v8" />
          </svg>
          <p className="text-lg text-slate-600 mb-1">No picks found</p>
          <p className="text-sm text-slate-400">Week {week}, {season}</p>
        </div>
      ) : (
        <div className="space-y-6">
          {groupedByWeek.map(([w, items]) => (
            <div key={w} className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-semibold">Week {w}</h2>
                <div className="text-sm text-slate-500">
                  {items.filter(i => i.isCorrect === true).length} correct / {items.length} picks
                </div>
              </div>

              <div className="space-y-3">
                {items.map(renderPickCard)}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default PickHistoryPage;
