import React, { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowPathIcon, CheckIcon } from '@heroicons/react/24/solid';

export interface PickSelectorProps {
  game: {
    id: string;
    homeTeam: { id: string; name: string; abbreviation: string; logoUrl?: string };
    awayTeam: { id: string; name: string; abbreviation: string; logoUrl?: string };
    isLocked: boolean;
  };
  currentPick?: {
    teamId: string;
    autoGenerated?: boolean;
  };
  onPickSubmit: (teamId: string) => Promise<void>;
  disabled?: boolean;
}

type ErrorBoundaryState = { hasError: boolean; message?: string };

class ErrorBoundary extends React.Component<{ children: React.ReactNode; componentName?: string }, ErrorBoundaryState> {
  constructor(props: { children: React.ReactNode; componentName?: string }) {
    super(props);
    this.state = { hasError: false, message: undefined };
  }

  static getDerivedStateFromError(err: unknown): ErrorBoundaryState {
    return { hasError: true, message: err instanceof Error ? err.message : 'Unknown error' };
  }

  componentDidCatch(error: unknown) {
    // Log to monitoring here if desired
    // console.error('PickSelector error:', error);
  }

  render() {
    if (this.state.hasError) {
      return (
        <div className="rounded-md border border-red-300 bg-red-50 p-3 text-sm text-red-700">
          <p className="font-medium">
            {(this.props.componentName ?? 'Component')} failed to load.
          </p>
          {this.state.message ? <p className="mt-1">{this.state.message}</p> : null}
        </div>
      );
    }
    return this.props.children as JSX.Element;
  }
}

function TeamAvatar(props: { name: string; abbreviation: string; logoUrl?: string }) {
  const { name, abbreviation, logoUrl } = props;
  if (logoUrl) {
    return (
      <img
        src={logoUrl}
        alt={`${name} logo`}
        className="h-6 w-6 rounded object-contain"
        referrerPolicy="no-referrer"
      />
    );
  }
  return (
    <div
      aria-hidden="true"
      className="flex h-6 w-6 items-center justify-center rounded bg-gray-200 text-[10px] font-semibold text-gray-700"
      title={name}
    >
      {abbreviation.toUpperCase()}
    </div>
  );
}

const PickSelectorInner = (props: PickSelectorProps) => {
  const { game, currentPick, onPickSubmit, disabled: externallyDisabled } = props;

  const [selectedTeamId, setSelectedTeamId] = useState<string | undefined>(currentPick?.teamId);
  const [submittingTeamId, setSubmittingTeamId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  // keep selected in sync when parent changes and not currently submitting
  useEffect(() => {
    if (!submittingTeamId) {
      setSelectedTeamId(currentPick?.teamId);
    }
  }, [currentPick?.teamId, submittingTeamId]);

  const isAuto = !!currentPick?.autoGenerated;
  const isLocked = game.isLocked || isAuto || !!externallyDisabled;
  const options = useMemo(
    () => [
      {
        id: game.homeTeam.id,
        label: game.homeTeam.name,
        abbr: game.homeTeam.abbreviation,
        logoUrl: game.homeTeam.logoUrl,
        side: 'Home' as const,
      },
      {
        id: game.awayTeam.id,
        label: game.awayTeam.name,
        abbr: game.awayTeam.abbreviation,
        logoUrl: game.awayTeam.logoUrl,
        side: 'Away' as const,
      },
    ],
    [game.homeTeam, game.awayTeam]
  );

  const groupRef = useRef<HTMLDivElement>(null);

  const handleSelect = useCallback(
    async (teamId: string) => {
      if (isLocked || submittingTeamId) return;
      setError(null);
      const prev = selectedTeamId;
      setSelectedTeamId(teamId); // optimistic
      setSubmittingTeamId(teamId);
      try {
        await onPickSubmit(teamId);
      } catch (e) {
        setSelectedTeamId(prev);
        const msg =
          e instanceof Error ? e.message : 'Could not save your pick. Please try again.';
        setError(msg);
      } finally {
        setSubmittingTeamId(null);
      }
    },
    [isLocked, submittingTeamId, selectedTeamId, onPickSubmit]
  );

  const onKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLDivElement>) => {
      if (isLocked) return;
      const ids = options.map((o) => o.id);
      const currentIndex = selectedTeamId ? ids.indexOf(selectedTeamId) : -1;

      if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
        e.preventDefault();
        const nextIndex = currentIndex <= 0 ? 0 : currentIndex - 1;
        handleSelect(ids[nextIndex] ?? ids[0]);
      } else if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
        e.preventDefault();
        const nextIndex =
          currentIndex < 0 ? 0 : Math.min(currentIndex + 1, ids.length - 1);
        handleSelect(ids[nextIndex] ?? ids[ids.length - 1]);
      } else if (e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        // Activate focused radio if any; fallback to current selection
        const activeEl = document.activeElement;
        const idx = options.findIndex(
          (o) => (activeEl as HTMLElement)?.dataset?.teamId === o.id
        );
        if (idx >= 0) {
          handleSelect(options[idx].id);
        } else if (selectedTeamId) {
          handleSelect(selectedTeamId);
        }
      }
    },
    [handleSelect, options, selectedTeamId, isLocked]
  );

  return (
    <div className="w-full">
      {isAuto && (
        <div
          className="mb-2 inline-flex items-center gap-1 rounded-full bg-purple-100 px-2 py-0.5 text-xs font-medium text-purple-800"
          aria-label="Auto-picked"
          title="Auto-picked"
        >
          AUTO
        </div>
      )}

      <div
        ref={groupRef}
        role="radiogroup"
        aria-label="Select your pick"
        aria-disabled={isLocked}
        onKeyDown={onKeyDown}
        className="grid grid-cols-2 gap-2"
      >
        {options.map((opt) => {
          const isSelected = selectedTeamId === opt.id;
          const isLoading = submittingTeamId === opt.id;
          const base =
            'relative flex min-h-[44px] items-center justify-between gap-2 rounded-md border px-3 py-2 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 transition-colors';
          const interactive = !isSelected
            ? 'bg-white hover:bg-blue-50 border-gray-300 text-gray-900'
            : 'bg-blue-600 border-blue-600 text-white';
          const disabledCls = isLocked ? 'opacity-60 cursor-not-allowed bg-gray-200 text-gray-600 border-gray-300 hover:bg-gray-200' : '';
          return (
            <button
              key={opt.id}
              type="button"
              role="radio"
              aria-checked={isSelected}
              aria-disabled={isLocked || undefined}
              data-team-id={opt.id}
              onClick={() => handleSelect(opt.id)}
              disabled={isLocked}
              className={`${base} ${interactive} ${disabledCls}`}
            >
              <div className="flex items-center gap-2">
                <TeamAvatar name={opt.label} abbreviation={opt.abbr} logoUrl={opt.logoUrl} />
                <div className="flex flex-col text-left leading-tight">
                  <span className={`text-sm font-semibold ${isSelected ? 'text-white' : 'text-gray-900'}`}>
                    {opt.label}
                  </span>
                  <span className={`text-xs ${isSelected ? 'text-blue-100' : 'text-gray-500'}`}>
                    {opt.side} • {opt.abbr}
                  </span>
                </div>
              </div>
              <div className="ml-2">
                {isSelected ? (
                  <CheckIcon className="h-5 w-5 text-white" aria-hidden="true" />
                ) : (
                  <span className="sr-only">Select {opt.label}</span>
                )}
              </div>

              {isLoading && (
                <div
                  className="absolute inset-0 z-10 flex items-center justify-center rounded-md bg-black/10"
                  aria-live="polite"
                  aria-label="Saving pick"
                >
                  <ArrowPathIcon className="h-5 w-5 animate-spin text-white drop-shadow" />
                </div>
              )}
            </button>
          );
        })}
      </div>

      {game.isLocked && !isAuto && (
        <p className="mt-2 text-xs text-gray-500" aria-live="polite">
          This game is locked. Picks can no longer be changed.
        </p>
      )}

      {error && (
        <div
          role="alert"
          className="mt-2 rounded-md border border-red-300 bg-red-100 px-3 py-2 text-sm text-red-800"
        >
          {error}
        </div>
      )}
    </div>
  );
};

const PickSelector = memo(PickSelectorInner);

const PickSelectorWithBoundary: React.FC<PickSelectorProps> = (props) => (
  <ErrorBoundary componentName="PickSelector">
    <PickSelector {...props} />
  </ErrorBoundary>
);

export default PickSelectorWithBoundary;
export { PickSelector as UnwrappedPickSelector };
