-- Create perfect picks for Week 1 for all users
-- Each user picks the winning team for every game

-- Dad's Week 1 picks
INSERT OR REPLACE INTO picks (id, userId, gameId, teamId, points, isCorrect, createdAt, updatedAt, isLocked, autoGenerated)
SELECT 
  'dad-week1-' || g.id as id,
  'dad-user-id' as userId,
  g.id as gameId,
  g.winnerTeamId as teamId,
  1 as points,
  1 as isCorrect,
  datetime('now', '-7 days') as createdAt,
  datetime('now', '-7 days') as updatedAt,
  1 as isLocked,
  0 as autoGenerated
FROM games g
WHERE g.week = 1 AND g.season = 2025 AND g.winnerTeamId IS NOT NULL;

-- Mom's Week 1 picks
INSERT OR REPLACE INTO picks (id, userId, gameId, teamId, points, isCorrect, createdAt, updatedAt, isLocked, autoGenerated)
SELECT 
  'mom-week1-' || g.id as id,
  'mom-user-id' as userId,
  g.id as gameId,
  g.winnerTeamId as teamId,
  1 as points,
  1 as isCorrect,
  datetime('now', '-7 days') as createdAt,
  datetime('now', '-7 days') as updatedAt,
  1 as isLocked,
  0 as autoGenerated
FROM games g
WHERE g.week = 1 AND g.season = 2025 AND g.winnerTeamId IS NOT NULL;

-- TwoBow's Week 1 picks
INSERT OR REPLACE INTO picks (id, userId, gameId, teamId, points, isCorrect, createdAt, updatedAt, isLocked, autoGenerated)
SELECT 
  'twobow-week1-' || g.id as id,
  'twobow-user-id' as userId,
  g.id as gameId,
  g.winnerTeamId as teamId,
  1 as points,
  1 as isCorrect,
  datetime('now', '-7 days') as createdAt,
  datetime('now', '-7 days') as updatedAt,
  1 as isLocked,
  0 as autoGenerated
FROM games g
WHERE g.week = 1 AND g.season = 2025 AND g.winnerTeamId IS NOT NULL;

-- RockyDaRock's Week 1 picks
INSERT OR REPLACE INTO picks (id, userId, gameId, teamId, points, isCorrect, createdAt, updatedAt, isLocked, autoGenerated)
SELECT 
  'rocky-week1-' || g.id as id,
  'rocky-user-id' as userId,
  g.id as gameId,
  g.winnerTeamId as teamId,
  1 as points,
  1 as isCorrect,
  datetime('now', '-7 days') as createdAt,
  datetime('now', '-7 days') as updatedAt,
  1 as isLocked,
  0 as autoGenerated
FROM games g
WHERE g.week = 1 AND g.season = 2025 AND g.winnerTeamId IS NOT NULL;

-- Create perfect picks for Week 2 for all users

-- Dad's Week 2 picks
INSERT OR REPLACE INTO picks (id, userId, gameId, teamId, points, isCorrect, createdAt, updatedAt, isLocked, autoGenerated)
SELECT 
  'dad-week2-' || g.id as id,
  'dad-user-id' as userId,
  g.id as gameId,
  g.winnerTeamId as teamId,
  1 as points,
  1 as isCorrect,
  datetime('now', '-3 days') as createdAt,
  datetime('now', '-3 days') as updatedAt,
  1 as isLocked,
  0 as autoGenerated
FROM games g
WHERE g.week = 2 AND g.season = 2025 AND g.winnerTeamId IS NOT NULL;

-- Mom's Week 2 picks
INSERT OR REPLACE INTO picks (id, userId, gameId, teamId, points, isCorrect, createdAt, updatedAt, isLocked, autoGenerated)
SELECT 
  'mom-week2-' || g.id as id,
  'mom-user-id' as userId,
  g.id as gameId,
  g.winnerTeamId as teamId,
  1 as points,
  1 as isCorrect,
  datetime('now', '-3 days') as createdAt,
  datetime('now', '-3 days') as updatedAt,
  1 as isLocked,
  0 as autoGenerated
FROM games g
WHERE g.week = 2 AND g.season = 2025 AND g.winnerTeamId IS NOT NULL;

-- TwoBow's Week 2 picks
INSERT OR REPLACE INTO picks (id, userId, gameId, teamId, points, isCorrect, createdAt, updatedAt, isLocked, autoGenerated)
SELECT 
  'twobow-week2-' || g.id as id,
  'twobow-user-id' as userId,
  g.id as gameId,
  g.winnerTeamId as teamId,
  1 as points,
  1 as isCorrect,
  datetime('now', '-3 days') as createdAt,
  datetime('now', '-3 days') as updatedAt,
  1 as isLocked,
  0 as autoGenerated
FROM games g
WHERE g.week = 2 AND g.season = 2025 AND g.winnerTeamId IS NOT NULL;

-- RockyDaRock's Week 2 picks
INSERT OR REPLACE INTO picks (id, userId, gameId, teamId, points, isCorrect, createdAt, updatedAt, isLocked, autoGenerated)
SELECT 
  'rocky-week2-' || g.id as id,
  'rocky-user-id' as userId,
  g.id as gameId,
  g.winnerTeamId as teamId,
  1 as points,
  1 as isCorrect,
  datetime('now', '-3 days') as createdAt,
  datetime('now', '-3 days') as updatedAt,
  1 as isLocked,
  0 as autoGenerated
FROM games g
WHERE g.week = 2 AND g.season = 2025 AND g.winnerTeamId IS NOT NULL;