import React, { useState, useEffect, useCallback, useRef } from 'react';
import { CountdownTimer } from '../CountdownTimer';
import { formatGameDate } from '../../utils/timeUtils';
import { ArrowPathIcon, XMarkIcon } from '@heroicons/react/24/solid';

export interface MobilePickModalProps {
  isOpen: boolean;
  onClose: () => void;
  game: {
    id: string;
    homeTeam: { id: string; name: string; abbreviation: string; logoUrl?: string };
    awayTeam: { id: string; name: string; abbreviation: string; logoUrl?: string };
    gameDate: string;
    homeSpread?: number;
    overUnder?: number;
    isLocked: boolean;
  };
  currentPick?: { teamId: string; autoGenerated?: boolean };
  onPickSubmit: (teamId: string) => Promise<void>;
}

export const MobilePickModal: React.FC<MobilePickModalProps> = ({
  isOpen,
  onClose,
  game,
  currentPick,
  onPickSubmit
}) => {
  const [selectedTeamId, setSelectedTeamId] = useState<string | undefined>(currentPick?.teamId);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isAnimating, setIsAnimating] = useState(false);
  const modalRef = useRef<HTMLDivElement>(null);

  // Sync selected team with current pick when modal opens
  useEffect(() => {
    if (isOpen) {
      setSelectedTeamId(currentPick?.teamId);
      setError(null);
      setIsAnimating(true);
    } else {
      // Delay animation state reset to allow exit animation
      setTimeout(() => setIsAnimating(false), 300);
    }
  }, [isOpen, currentPick?.teamId]);

  // Handle escape key press
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen && !isSubmitting) {
        onClose();
      }
    };

    document.addEventListener('keydown', handleEscape);
    return () => document.removeEventListener('keydown', handleEscape);
  }, [isOpen, isSubmitting, onClose]);

  // Prevent body scroll when modal is open
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
      // Add safe area padding for iOS
      document.body.style.paddingBottom = 'env(safe-area-inset-bottom)';
    } else {
      document.body.style.overflow = '';
      document.body.style.paddingBottom = '';
    }

    return () => {
      document.body.style.overflow = '';
      document.body.style.paddingBottom = '';
    };
  }, [isOpen]);

  // Focus management with focus trap
  useEffect(() => {
    if (!isOpen || !modalRef.current) return;

    const modal = modalRef.current;
    const focusableElements = modal.querySelectorAll(
      'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])'
    );
    const firstElement = focusableElements[0] as HTMLElement;
    const lastElement = focusableElements[focusableElements.length - 1] as HTMLElement;

    // Focus first element
    setTimeout(() => firstElement?.focus(), 100);

    // Trap focus within modal
    const handleTabKey = (e: KeyboardEvent) => {
      if (e.key !== 'Tab') return;

      if (e.shiftKey) {
        // Shift + Tab
        if (document.activeElement === firstElement) {
          e.preventDefault();
          lastElement?.focus();
        }
      } else {
        // Tab
        if (document.activeElement === lastElement) {
          e.preventDefault();
          firstElement?.focus();
        }
      }
    };

    modal.addEventListener('keydown', handleTabKey);
    return () => modal.removeEventListener('keydown', handleTabKey);
  }, [isOpen]);

  const handleTeamSelect = useCallback((teamId: string) => {
    if (game.isLocked || isSubmitting) return;
    setSelectedTeamId(teamId);
    setError(null);
  }, [game.isLocked, isSubmitting]);

  const handleSubmit = useCallback(async () => {
    if (!selectedTeamId || game.isLocked || isSubmitting) return;

    setIsSubmitting(true);
    setError(null);

    try {
      await onPickSubmit(selectedTeamId);
      // Close modal on success
      onClose();
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to save your pick. Please try again.';
      setError(message);
    } finally {
      setIsSubmitting(false);
    }
  }, [selectedTeamId, game.isLocked, isSubmitting, onPickSubmit, onClose]);

  const handleBackdropClick = useCallback((e: React.MouseEvent) => {
    if (e.target === e.currentTarget && !isSubmitting) {
      onClose();
    }
  }, [isSubmitting, onClose]);

  const formatSpread = (spread: number): string => {
    const sign = spread > 0 ? '+' : '';
    return `${sign}${spread.toFixed(1)}`;
  };

  const TeamOption: React.FC<{
    team: typeof game.homeTeam;
    isHome: boolean;
    spread?: number;
  }> = ({ team, isHome, spread }) => {
    const isSelected = selectedTeamId === team.id;
    const isCurrentPick = currentPick?.teamId === team.id;

    return (
      <button
        type="button"
        onClick={() => handleTeamSelect(team.id)}
        disabled={game.isLocked || isSubmitting}
        className={`
          relative flex items-center gap-4 p-4 rounded-xl border-2 transition-all duration-200
          min-h-[88px] w-full touch-manipulation
          ${isSelected
            ? 'border-blue-600 bg-blue-50 shadow-lg scale-105'
            : 'border-gray-200 bg-white hover:border-gray-300 active:bg-gray-50'
          }
          ${game.isLocked || isSubmitting ? 'opacity-60 cursor-not-allowed' : 'cursor-pointer'}
        `}
        aria-label={`Select ${team.name}`}
        aria-pressed={isSelected}
      >
        {/* Team Logo - Touch optimized */}
        <div className={`
          w-16 h-16 rounded-full flex items-center justify-center flex-shrink-0 overflow-hidden
          ${isSelected ? 'bg-blue-100' : 'bg-gray-100'}
        `}>
          {team.logoUrl ? (
            <img
              src={team.logoUrl}
              alt={`${team.name} logo`}
              className="w-12 h-12 object-contain"
              onError={(e) => {
                e.currentTarget.style.display = 'none';
                e.currentTarget.nextElementSibling!.style.display = 'flex';
              }}
            />
          ) : null}
          <div
            className={`w-12 h-12 rounded-full flex items-center justify-center text-sm font-bold ${
              isSelected ? 'text-blue-600' : 'text-gray-600'
            } ${team.logoUrl ? 'hidden' : 'flex'}`}
            style={{ display: team.logoUrl ? 'none' : 'flex' }}
          >
            {team.abbreviation}
          </div>
        </div>

        {/* Team Info */}
        <div className="flex-1 text-left min-w-0">
          <div className={`font-bold text-lg mb-0.5 ${isSelected ? 'text-blue-900' : 'text-gray-900'}`}>
            {team.name}
          </div>
          <div className="flex items-center gap-2 text-sm">
            <span className={isSelected ? 'text-blue-700' : 'text-gray-600'}>
              {isHome ? 'Home' : 'Away'}
            </span>
            <span className="w-1 h-1 bg-gray-300 rounded-full"></span>
            <span className={`font-medium ${isSelected ? 'text-blue-700' : 'text-gray-600'}`}>
              {team.abbreviation}
            </span>
          </div>
          {spread !== undefined && (
            <div className={`text-sm font-medium mt-1 ${isSelected ? 'text-blue-600' : 'text-gray-500'}`}>
              Spread: {formatSpread(spread)}
            </div>
          )}
        </div>

        {/* Selection Indicator */}
        <div className={`
          w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 transition-all duration-200
          ${isSelected ? 'bg-blue-600 scale-110' : 'bg-gray-200'}
        `}>
          {isSelected ? (
            <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
            </svg>
          ) : (
            <div className="w-4 h-4 rounded-full border-2 border-gray-400"></div>
          )}
        </div>

        {/* Current pick badge */}
        {isCurrentPick && !isSelected && (
          <div className="absolute top-2 right-2 px-2 py-0.5 bg-green-100 text-green-800 text-xs font-medium rounded-full">
            Current
          </div>
        )}
      </button>
    );
  };

  if (!isOpen && !isAnimating) return null;

  return (
    <div
      className={`
        fixed inset-0 z-50 flex items-end sm:items-center justify-center
        transition-all duration-300
        ${isOpen ? 'opacity-100' : 'opacity-0'}
      `}
      role="dialog"
      aria-modal="true"
      aria-labelledby="pick-modal-title"
      onClick={handleBackdropClick}
    >
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/50 backdrop-blur-sm"></div>

      {/* Modal Container - Bottom sheet on mobile, centered on larger screens */}
      <div
        ref={modalRef}
        className={`
          relative w-full max-w-lg bg-white rounded-t-2xl sm:rounded-2xl shadow-2xl
          max-h-[85vh] flex flex-col
          transition-all duration-300 ease-out
          ${isOpen
            ? 'translate-y-0 sm:translate-y-0'
            : 'translate-y-full sm:translate-y-8'
          }
        `}
        style={{
          paddingBottom: 'env(safe-area-inset-bottom)'
        }}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-gray-200 flex-shrink-0">
          <div className="flex-1 min-w-0">
            <h2 id="pick-modal-title" className="text-lg font-bold text-gray-900 truncate">
              Make Your Pick
            </h2>
            <p className="text-sm text-gray-600 truncate">
              {formatGameDate(game.gameDate, true)}
            </p>
          </div>

          {/* Close button - Touch optimized */}
          <button
            onClick={onClose}
            disabled={isSubmitting}
            className="w-10 h-10 rounded-full flex items-center justify-center text-gray-500 hover:bg-gray-100 active:bg-gray-200 transition-colors flex-shrink-0 ml-2 touch-manipulation"
            aria-label="Close modal"
          >
            <XMarkIcon className="w-6 h-6" />
          </button>
        </div>

        {/* Countdown Timer - Prominent */}
        <div className="px-4 py-3 bg-blue-50 border-b border-blue-100 flex-shrink-0">
          <div className="flex items-center justify-center gap-2">
            <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span className="text-sm font-medium text-blue-900">Time to lock:</span>
            <CountdownTimer
              targetTime={game.gameDate}
              mode="detailed"
              className="text-blue-900"
            />
          </div>
        </div>

        {/* Content - Scrollable */}
        <div className="flex-1 overflow-y-auto px-4 py-4">
          <div className="space-y-3">
            {/* Away Team */}
            <TeamOption
              team={game.awayTeam}
              isHome={false}
              spread={game.homeSpread ? -game.homeSpread : undefined}
            />

            {/* VS Divider */}
            <div className="flex items-center justify-center py-1">
              <div className="h-px bg-gray-200 flex-1"></div>
              <span className="px-3 text-sm font-semibold text-gray-400">VS</span>
              <div className="h-px bg-gray-200 flex-1"></div>
            </div>

            {/* Home Team */}
            <TeamOption
              team={game.homeTeam}
              isHome={true}
              spread={game.homeSpread}
            />

            {/* Over/Under Display */}
            {game.overUnder && (
              <div className="text-center py-2 text-sm text-gray-600">
                Over/Under: <span className="font-semibold">{game.overUnder.toFixed(1)}</span>
              </div>
            )}
          </div>

          {/* Error Message */}
          {error && (
            <div
              role="alert"
              className="mt-4 p-3 bg-red-50 border border-red-200 rounded-lg"
            >
              <div className="flex items-start gap-2">
                <svg className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <p className="text-sm text-red-800 flex-1">{error}</p>
              </div>
            </div>
          )}
        </div>

        {/* Footer - Action Buttons */}
        <div className="flex gap-3 p-4 border-t border-gray-200 bg-gray-50 flex-shrink-0">
          <button
            onClick={onClose}
            disabled={isSubmitting}
            className="flex-1 min-h-[48px] px-4 py-3 bg-white border-2 border-gray-300 text-gray-700 font-semibold rounded-lg hover:bg-gray-50 active:bg-gray-100 transition-colors disabled:opacity-60 disabled:cursor-not-allowed touch-manipulation"
            aria-label="Cancel"
          >
            Cancel
          </button>

          <button
            onClick={handleSubmit}
            disabled={!selectedTeamId || game.isLocked || isSubmitting}
            className="flex-1 min-h-[48px] px-4 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 active:bg-blue-800 transition-colors disabled:opacity-60 disabled:cursor-not-allowed flex items-center justify-center gap-2 touch-manipulation"
            aria-label="Confirm pick"
          >
            {isSubmitting ? (
              <>
                <ArrowPathIcon className="w-5 h-5 animate-spin" />
                Saving...
              </>
            ) : (
              <>
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                Confirm Pick
              </>
            )}
          </button>
        </div>

        {/* Lock warning */}
        {game.isLocked && (
          <div className="px-4 py-3 bg-orange-50 border-t border-orange-200 flex-shrink-0">
            <div className="flex items-center gap-2 text-orange-800">
              <svg className="w-5 h-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
              </svg>
              <p className="text-sm font-medium">
                This game is locked. Picks can no longer be changed.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
